services:
  webui:
    build: .
    container_name: turbodiffusion-webui-1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - CUDA_HOME=/usr/local/cuda
      - TORCH_CUDA_ARCH_LIST=12.0
    volumes:
      - ./outputs:/workspace/TurboDiffusion/outputs
    working_dir: /workspace/TurboDiffusion
    ports:
      - "17860:7860"
